name: profile
description: User profile and capability management features
publish_to: 'none'
resolution: workspace
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  url_launcher: ^6.3.1
  shared:
    path: ../../shared
  core:
    path: ../../core

  video_window_client: any
  serverpod_flutter: any
  image_picker: any
  crop_your_image: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  flutter_lints: ^3.0.0

flutter:
  generate: true

