name: timeline
description: Video feed timeline feature for Video Window
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  video_player: ^2.8.1
  infinite_scroll_pagination: ^4.0.0
  wakelock_plus: ^1.2.5
  flutter_displaymode: ^0.6.0
  visibility_detector: ^0.4.2
  cached_network_image: ^3.3.1
  flutter_secure_storage: ^4.2.1
  connectivity_plus: ^6.1.0
  battery_plus: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  core:
    path: ../../core
  shared:
    path: ../../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

flutter:
  generate: true

