name: auth
description: Authentication feature for Video Window
publish_to: 'none'
resolution: workspace
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  core:
    path: ../../core
  shared:
    path: ../../shared

  sign_in_with_apple: any
  google_sign_in: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.4
  mocktail: ^1.0.0
